version: '3.8'

services:
  # This is a placeholder - Tauri apps are built locally, not in containers
  # Use this if you want to set up a build environment in Docker
  
  builder:
    image: rust:latest
    working_dir: /app
    volumes:
      - .:/app
    command: /bin/bash -c "echo 'Use cargo tauri build to build the application'"

